import movie
import fresh_tomatoes


# Create an array of objects for each title
movies = [
          movie.Movie("Phil Knight Interview",
                      "thumbs/phil-knight.jpg",
                      "https://www.youtube.com/watch?v=LBLenh_8d3E"),
          movie.Movie("Kitchen Project",
                      "thumbs/kitchen-project-sm.jpg",
                      "https://www.youtube.com/watch?v=vp3bfDAYxGk"),
          movie.Movie("Servant Teams",
                      "thumbs/servant-teams-sm.jpg",
                      "https://www.youtube.com/watch?v=dmFLbTmE6W0"),
          movie.Movie("Blessed",
                      "thumbs/blessed-sm.jpg",
                      "https://www.youtube.com/watch?v=j9Ih7GV6CLM"),
          movie.Movie("Tiny House Hotel",
                      "thumbs/tiny-houses.jpg",
                      "https://www.youtube.com/watch?v=2izBbWtgBcY"),
          movie.Movie("BEV Fund",
                      "thumbs/bill-and-friends.jpg",
                      "https://www.youtube.com/watch?v=FG4QuaZAivk"),
          movie.Movie("Google Cuba",
                      "thumbs/google-cuba.jpg",
                      "https://www.youtube.com/watch?v=uYfgKNuWp7w"),
          movie.Movie("50 Percent Chicken",
                      "thumbs/50-percent-chicken.jpg",
                      "https://www.youtube.com/watch?v=tF604My_Lc0"),
          movie.Movie("Encrypted Web",
                      "thumbs/encrypted-web.jpg",
                      "https://www.youtube.com/watch?v=hFz6TPPBpmk"),
          movie.Movie("Zealandia",
                      "thumbs/zealandia.jpg",
                      "https://www.youtube.com/watch?v=SRkbl5zb4qU"),
          movie.Movie("Jewel Clouds",
                      "thumbs/jewel-clouds.jpg",
                      "https://www.youtube.com/watch?v=Q1Yon9XIv20"),
          movie.Movie("World Unemployment",
                      "thumbs/world.jpg",
                      "https://www.youtube.com/watch?v=oHXNPbh5-dk"),
          movie.Movie("Antimatter",
                      "thumbs/antimatter.jpg",
                      "https://www.youtube.com/watch?v=pIhYlY0xcuM"),
          movie.Movie("New Elements",
                      "thumbs/new-elements.jpg",
                      "https://www.youtube.com/watch?v=hwEbi_AR9wQ"),
          movie.Movie("Best Student Cities",
                      "thumbs/best-student-cities.jpg",
                      "https://www.youtube.com/watch?v=QX6QuVmm6Z0?t=26s"),
          movie.Movie("Refuel Craft",
                      "thumbs/refuel-craft.jpg",
                      "https://www.youtube.com/watch?v=wnMvkAmxmRI"),
          movie.Movie("Murder Rates",
                      "thumbs/murder-rates.jpg",
                      "https://www.youtube.com/watch?v=t3G9jemlSsA"),
          movie.Movie("Anchient Nesting Doll",
                      "thumbs/ancient-nesting-doll.jpg",
                      "https://www.youtube.com/watch?v=9l1A5REcNas"),
          # movie.Movie("",
          #             "",
          #             ""),
          # movie.Movie("",
          #             "",
          #             ""),
          # movie.Movie("",
          #             "",
          #             ""),
          # movie.Movie("",
          #             "",
          #             ""),
          ]

# Build the movie trailer website
fresh_tomatoes.open_movies_page(movies)
